### ISSUE TITLE
前端使用 PrintJS 打印的二三件小事

### ISSUE THREAD

**Issue by jimdeng92** [jimdeng92/Blog#34]
首先 我们知道使用 PrintJS 实现打印 HTML 非常的简单

``` js
import printJS from 'print-js';

printJS({
    printable: 'printLayout',
    type: 'html',
    targetStyles: ['*'], // 一般是必须的，它使html中的样式都复制到打印的文档中
    style: '@media print{@page {margin: 10mm 7mm; size: A4 portrait}}', // size 有很多配置项，这里的意思是纵向打印的A4纸，横向：landscape
  });
```

这样就能实现打印 HTML 了，很多大事 PrintJS 已经替我们解决了，但还有几件小事需要留意。

1. 如果文档中包含了背景色，而你在打印的时候刚好需要。除了每次要求用户点击选中打印中的“背景图形”外。

![image](https://github.com/jimdeng92/Blog/assets/31594692/bc2d2033-9f22-4875-ab45-946cb8a57f3d)

你只需要在对应的元素上添加 css 属性  `-webkit-print-color-adjust: exact;`。

``` css
.gray-bg {
  background-color: #cfcfcf;
  -webkit-print-color-adjust: exact;
}
```

![image](https://github.com/jimdeng92/Blog/assets/31594692/02f5b274-97ae-4373-b4f7-c6bec765235a)

2. 当你的文档中拥有不同的 fontSize 时，PrintJS 1.6.x 会忽略掉你的 css 设置。网络上大部分的解决方案都教你修改源码，但这实在不是什么好的策略，我们只需要使用 `transform: scale(1.4);` 放大或缩小显示就成了。

``` css
.fz-18 {
  font-size: 12px;
  transform: scale(1.5);
}
```

3. 如果需要分页打印时，虽然我们知道每张A4纸的尺寸是 210mm * 297mm，并且也设置了每一页的大小。但总是难免出现各种各样的Bug，导致某一页的内容被切割了，这同样可以通过 css 样式解决。

``` css
.page-item {
    height: 297mm;
    font-family: verdana, arial, sans-serif, 'Microsoft Yahei';
    /* 控制换页 */
    page-break-before: always;
```
